title: Here We Go
author: Malos
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  These are not normal times. The air is thick with the the delusion of growth and productivity.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
